-- Migration generated by Drizzle Kit (Manual Override)

DROP TABLE IF EXISTS "policies";

CREATE TABLE "policy_pages" (
	"id" integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	"url" text NOT NULL,
	"slug" text NOT NULL,
	"canonical_url" text,
	"policy_identifier" text,
	"source" text NOT NULL,
	"is_active" integer DEFAULT true NOT NULL,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "policy_pages_url_unique" ON "policy_pages" ("url");

CREATE TABLE "policy_versions" (
	"id" integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	"policy_page_id" integer NOT NULL,
	"version_number" integer NOT NULL,
	"content_markdown" text NOT NULL,
	"content_hash" text NOT NULL,
	"scraped_at" text NOT NULL,
	"effective_date" text,
	"superseded" integer DEFAULT false NOT NULL,
	"ai_keywords_json" text,
	"ai_metadata_json" text,
	FOREIGN KEY ("policy_page_id") REFERENCES "policy_pages" ("id") ON UPDATE no action ON DELETE no action
);

CREATE TABLE "policy_embeddings" (
	"id" integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	"policy_version_id" integer NOT NULL,
	"vector_id" text NOT NULL,
	"chunk_index" integer NOT NULL,
	"text_chunk" text NOT NULL,
	"created_at" text NOT NULL,
	FOREIGN KEY ("policy_version_id") REFERENCES "policy_versions" ("id") ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX "policy_embeddings_vector_id_unique" ON "policy_embeddings" ("vector_id");

CREATE TABLE "user_profiles" (
	"id" integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	"external_user_id" text NOT NULL,
	"birth_year" integer NOT NULL,
	"citizenship_country" text NOT NULL,
	"primary_residence_country" text NOT NULL,
	"intends_retire_in_singapore" integer DEFAULT false NOT NULL,
	"last_updated_at" text NOT NULL,
	"raw_profile_json" text
);
--> statement-breakpoint
CREATE UNIQUE INDEX "user_profiles_external_user_id_unique" ON "user_profiles" ("external_user_id");

CREATE TABLE "policy_user_impacts" (
	"id" integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	"user_profile_id" integer NOT NULL,
	"policy_version_id" integer NOT NULL,
	"analysis_model" text NOT NULL,
	"warnings_json" text NOT NULL,
	"benefits_json" text NOT NULL,
	"summary_json" text NOT NULL,
	"created_at" text NOT NULL,
	"last_refreshed_at" text NOT NULL,
	FOREIGN KEY ("user_profile_id") REFERENCES "user_profiles" ("id") ON UPDATE no action ON DELETE no action,
	FOREIGN KEY ("policy_version_id") REFERENCES "policy_versions" ("id") ON UPDATE no action ON DELETE no action
);

-- Seed Default User
INSERT INTO user_profiles (external_user_id, birth_year, citizenship_country, primary_residence_country, intends_retire_in_singapore, last_updated_at)
SELECT 'default', 1987, 'Singapore', 'United States', 1, datetime('now')
WHERE NOT EXISTS (SELECT 1 FROM user_profiles WHERE external_user_id = 'default');
