# -*- coding: utf-8 -*-
"""SG OpenData Collections

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RIYdsJ9Dv0aEmXNu-LX_NK7ys3YJN6TB
"""

# @title # CONFIGURATION & SECRETS { display-mode: "form" }
import os
import json
import time
import requests
import pandas as pd
import io
from google.colab import userdata
from google import genai
from google.genai import types

# ==========================================
# CONFIGURATION & SECRETS
# ==========================================
try:
    SG_DATA_API_KEY = userdata.get('SG_DATA_API_KEY')
    GOOGLE_API_KEY = userdata.get('GOOGLE_API_KEY')
except Exception as e:
    print("❌ Error: Please set 'SG_DATA_API_KEY' and 'GOOGLE_API_KEY' in Colab Secrets.")
    raise e

client = genai.Client(api_key=GOOGLE_API_KEY)

# @title #Singapore CollectionID & Gemini Model
COLLECTION_ID = 189 # @param {"type":"number","placeholder":"collection_id"}
GEMINI_MODEL = "gemini-2.0-flash" # @param ["gemini-2.0-flash","gemini-2.0-pro","gemini-2.5-flash","gemini-2.5-pro","gemini-3.0-flash","gemini-3.0-pro"]

# @title # HELPERS

# @markdown ---

# @markdown 1) Download Full CSV (download_full_dataset)
# @markdown 1) Pretty Print (pretty_print_json)
# @markdown ---

# ==========================================
# HELPER: Download Full CSV
# ==========================================
def download_full_dataset(dataset_id, api_key):
    """
    Implements the initiate -> poll -> download pattern to get the FULL CSV.
    """
    print(f"   ⬇️  Initiating download for {dataset_id}...")

    headers = {
        "Content-Type": "application/json",
        "x-api-key": api_key,
        "referer": "https://colab.research.google.com"
    }

    # 1. Initiate Download
    init_url = f"https://api-open.data.gov.sg/v1/public/api/datasets/{dataset_id}/initiate-download"
    try:
        init_resp = requests.get(init_url, headers=headers, json={})
        init_resp.raise_for_status()
    except Exception as e:
        print(f"      ❌ Failed to initiate: {e}")
        return None

    # 2. Poll for Result
    poll_url = f"https://api-open.data.gov.sg/v1/public/api/datasets/{dataset_id}/poll-download"
    max_polls = 10

    for i in range(max_polls):
        time.sleep(3) # Wait between polls
        try:
            poll_resp = requests.get(poll_url, headers=headers, json={})
            poll_data = poll_resp.json().get('data', {})

            if 'url' in poll_data:
                download_url = poll_data['url']
                print(f"      ✅ URL Ready. Downloading...")
                return pd.read_csv(download_url)
        except Exception as e:
            print(f"      ⚠️ Polling error: {e}")

    print("      ❌ Timeout: Download link never became ready.")
    return None

# ==========================================
# HELPER: Pretty Print JSON
# ==========================================
def pretty_print_json(response_json):
    """Pretty print JSON from a requests response object"""
    try:
        print(json.dumps(response_json, indent=4, sort_keys=True))
    except json.JSONDecodeError:
        print("Response is not valid JSON")
        print(response.text)

# @title # STEP 0: Fetch Collection Metadata


# ==========================================
# STEP 0: Fetch Collection Metadata
# ==========================================
print(f"--- STEP 0: Fetching Collection {COLLECTION_ID} ---")
collection_url = "https://api-production.data.gov.sg/v2/public/api/collections/{}/metadata".format(COLLECTION_ID)
coll_data = requests.get(collection_url).json()
pretty_print_json(coll_data)
child_datasets = coll_data['data']['collectionMetadata']['childDatasets']


print(f"Found {len(child_datasets)} datasets in collection.")

# @title Gemini Magic

# @markdown ---

# @markdown STEP 1: Gather Samples and Metadata for Gemini

# @markdown STEP 2: Generate Normalization Plan (Generic)

# @markdown ---

# ==========================================
# STEP 1: Gather Samples and Metadata for Gemini
# ==========================================
print("\n--- STEP 1: Gathering Samples and Metadata for AI Analysis ---")
schema_payload = {}

# Setup session with headers
s = requests.Session()
s.headers.update({'referer': 'https://colab.research.google.com'})
if SG_DATA_API_KEY and SG_DATA_API_KEY != "PASTE_API_KEY_HERE":
    s.headers['x-api-key'] = SG_DATA_API_KEY

base_url = "https://api-production.data.gov.sg"

for ds_id in child_datasets:
    try:
        # Fetch dataset metadata
        metadata_url = base_url + f"/v2/public/api/datasets/{ds_id}/metadata"
        metadata_resp = s.get(metadata_url)
        metadata_data = metadata_resp.json()['data']

        # Extract column information
        column_metadata = metadata_data.pop('columnMetadata', None)
        columns = list(column_metadata['map'].values()) if column_metadata else []

        # Fetch sample data
        sample_url = f"https://data.gov.sg/api/action/datastore_search?resource_id={ds_id}&limit=5"
        sample_resp = requests.get(sample_url).json()
        # pretty_print_json(sample_resp)

        if 'result' in sample_resp and 'records' in sample_resp['result']:
            schema_payload[ds_id] = {
                "metadata": {
                    "id": ds_id,
                    "name": metadata_data.get('name', ''),
                    "description": metadata_data.get('description', ''),
                    "coverageStart": metadata_data.get('coverageStart', ''),
                    "coverageEnd": metadata_data.get('coverageEnd', ''),
                    "lastUpdatedAt": metadata_data.get('lastUpdatedAt', ''),
                    "format": metadata_data.get('format', ''),
                    "columns": columns,
                    "totalRows": sample_resp['result']['total']
                },
                "sample_rows": sample_resp['result']['records']
            }
            print(f"✓ Fetched {ds_id}: {metadata_data.get('name', 'Unknown')}")

    except Exception as e:
        print(f"✗ Skipping {ds_id} (Fetch failed): {e}")

print(f"\n📊 Successfully gathered data from {len(schema_payload)} datasets")

# ==========================================
# STEP 2: Generate Normalization Plan (Generic)
# ==========================================
print("\n--- STEP 2: Generating Normalization Plan with Gemini ---")

# Modified schema - using array of mappings
normalization_schema = {
    "type": "object",
    "properties": {
        "normalized_columns": {
            "type": "array",
            "items": {"type": "string"},
            "description": "A list of unified, snake_case column names"
        },
        "mappings": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "dataset_id": {"type": "string"},
                    "dataset_name": {"type": "string"},
                    "column_mappings": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "original": {"type": "string"},
                                "normalized": {"type": "string"}
                            },
                            "required": ["original", "normalized"]
                        }
                    }
                },
                "required": ["dataset_id", "column_mappings"]
            }
        }
    },
    "required": ["normalized_columns", "mappings"]
}

prompt_context = json.dumps(schema_payload, indent=2)
prompt_text = f"""
You are a generic Data Engineering Agent.
I have provided a dictionary of datasets belonging to a single collection.
They likely contain similar data (e.g., the same metrics over different time periods), but the column headers may vary, have typos, or use different casing.

Here is the data context including:
- Full metadata for each dataset (name, description, coverage dates, columns)
- 5 sample rows per dataset

Data:
{prompt_context}

YOUR TASK:
1. **Analyze** the column headers and data content across all datasets to understand the underlying concepts.
   - Pay attention to the dataset names and descriptions to understand the context
   - Consider the coverage periods to understand how data might have evolved
   - Use the column metadata to understand expected column names

2. **Unify** these concepts into a single "Master Schema" of normalized snake_case column names.
   - Prefer descriptive names that capture the semantic meaning
   - Be consistent with naming conventions across similar columns

3. **Map** every original column in every dataset to your new Master Schema.
   - If a column only exists in one dataset, keep it (normalize the name)
   - If a column is just a different name for the same concept (e.g. "price" vs "resale_price"), map them to the same normalized name
   - Consider the dataset context when determining if columns are the same concept

The column_mappings should be an array of objects, each with "original" (the original column name) and "normalized" (the new normalized name).

Output MUST strictly follow the provided JSON schema.
"""

response = client.models.generate_content(
    model=GEMINI_MODEL,
    contents=prompt_text,
    config=types.GenerateContentConfig(
        response_mime_type='application/json',
        response_schema=normalization_schema
    )
)

# Parse the Structured Response
if not response.text:
    print("❌ Error: Empty response from AI.")
    exit()

try:
    plan = json.loads(response.text)

    # Convert the array-based mappings to nested dict for O(1) lookup
    mappings_dict = {}
    for item in plan.get("mappings", []):
        dataset_id = item['dataset_id']
        dataset_name = item.get('dataset_name', '')
        mappings_dict[dataset_id] = {
            'name': dataset_name,
            'mappings': {}
        }
        for mapping in item['column_mappings']:
            mappings_dict[dataset_id]['mappings'][mapping['original']] = mapping['normalized']

    normalized_cols = plan.get("normalized_columns", [])
    print(f"\n✅ Schema Discovered: Found {len(normalized_cols)} normalized columns.")
    print(f"   Columns: {normalized_cols}")

    # Display mapping summary
    print("\n📋 Dataset Mappings Summary:")
    for ds_id, info in mappings_dict.items():
        print(f"   - {info['name'] or ds_id}: {len(info['mappings'])} columns mapped")

    # Pretty Print
    pretty_print_json(mappings_dict)

except json.JSONDecodeError as e:
    print(f"❌ Error: Invalid JSON from AI.\n{response.text}")
    exit()

# @title # STEP 3: Download FULL Data & Normalize
# ==========================================
# STEP 3: Download FULL Data & Normalize
# ==========================================
print("\n--- STEP 3: Downloading & Normalizing FULL Datasets ---")
master_frames = []

for ds_id in child_datasets:  # child_datasets is already a list of strings
    if ds_id not in mappings_dict:
        print(f"Skipping {ds_id}: AI did not provide a mapping.")
        continue

    # 1. Download FULL CSV
    df = download_full_dataset(ds_id, SG_DATA_API_KEY)

    if df is not None:
        # 2. Rename Columns based on AI Map
        column_map = mappings_dict[ds_id]['mappings']  # Access the 'mappings' key
        # Only rename columns that actually exist in this dataframe
        valid_renames = {k: v for k, v in column_map.items() if k in df.columns}
        df.rename(columns=valid_renames, inplace=True)

        # 3. Inject Metadata
        df['meta_source_dataset_id'] = ds_id
        df['meta_dataset_name'] = mappings_dict[ds_id]['name']  # Add dataset name

        # If you have coverage dates from schema_payload, use those
        # Otherwise, you might need to fetch them again or store them earlier
        if ds_id in schema_payload:
            df['meta_coverage_start'] = schema_payload[ds_id]['metadata'].get('coverageStart')
            df['meta_coverage_end'] = schema_payload[ds_id]['metadata'].get('coverageEnd')

        # 4. Enforce Schema (Add missing columns as NaN)
        for col in normalized_cols:
            if col not in df.columns:
                df[col] = None

        # 5. Reorder & Filter
        keep_cols = normalized_cols + ['meta_source_dataset_id', 'meta_dataset_name', 'meta_coverage_start', 'meta_coverage_end']
        final_cols = [c for c in keep_cols if c in df.columns]
        df = df[final_cols]

        print(f"      ✨ Processed {len(df):,} rows from {mappings_dict[ds_id]['name']}")
        master_frames.append(df)

# @title # STEP 4: Merge & Validate
# ==========================================
# STEP 4: Merge & Validate
# ==========================================
print("\n--- STEP 4: Merging Results ---")

if master_frames:
    master_df = pd.concat(master_frames, ignore_index=True)
    print(f"✅ FINAL DATASET READY: {len(master_df):,} total rows.")
    print("Sample Data:")
    display(master_df.head())

    print("\nColumn Data Types:")
    print(master_df.dtypes)
else:
    print("❌ No data was downloaded or processed.")

