import { sqliteTable, text, integer, real } from 'drizzle-orm/sqlite-core';
import { type InferSelectModel, type InferInsertModel } from 'drizzle-orm';
import { rawHdbPropertyInfo } from './schema';

/**
 * **Enriched HDB Blocks**
 * * The Master Record for every physical HDB block in Singapore.
 * * Contains geocoordinates and unit composition.
 * * @ai_usage Query this to find specific buildings. Filter by `town` or `max_floor_lvl`.
 * * Use `latitude`/`longitude` for radius searches.
 */
export const enrichedHdbBlocks = sqliteTable('enriched_hdb_blocks', {
    id: integer('id').primaryKey(),
    rawPropertyId: integer('raw_property_id').references(() => rawHdbPropertyInfo.id),
    block: text('block').notNull(),
    street: text('street').notNull(),
    town: text('town').notNull(),
    postalCode: text('postal_code'),
    latitude: real('latitude'), // CRITICAL for mapping
    longitude: real('longitude'),
    yearCompleted: integer('year_completed'),
    // Determining "Rarity"
    totalUnits: integer('total_units'),
    hasCommercial: integer('has_commercial', { mode: 'boolean' }),
});

/**
 * **Block Amenities Cache**
 * * Pre-computed distances to key lifestyle nodes.
 * * @ai_usage Use to answer "How close is the nearest MRT?". Filter by `amenity_type`.
 */
export const enrichedBlockAmenities = sqliteTable('enriched_block_amenities', {
    id: integer('id').primaryKey(),
    blockId: integer('block_id').references(() => enrichedHdbBlocks.id),
    amenityType: text('amenity_type').notNull(), // 'MRT', 'HAWKER', 'BUS'
    amenityName: text('amenity_name').notNull(),
    distanceMeters: real('distance_meters').notNull(),
    isSheltered: integer('is_sheltered', { mode: 'boolean' }), // Bonus if you can infer this
});

/**
 * **Block Market Metrics**
 * * Financial performance of specific blocks.
 * * @ai_usage Use for "High Yield" or "Undervalued" queries.
 */
export const analyticsBlockMetrics = sqliteTable('analytics_block_metrics', {
    id: integer('id').primaryKey(),
    blockId: integer('block_id').references(() => enrichedHdbBlocks.id),
    lastUpdated: text('last_updated'),

    // Financials
    medianResalePrice: real('median_resale_price'),
    medianRent: real('median_rent'),
    impliedRentalYield: real('implied_rental_yield'), // The "Investor" metric
    pricePerSqm: real('price_per_sqm'),

    // Liquidity
    salesVolumeLastYear: integer('sales_volume_last_year'),

    // Scores (0-10)
    walkabilityScore: real('walkability_score'),
    foodAccessScore: real('food_access_score'),
});

/**
 * **Neighborhood Scores**
 * * Aggregated metrics for neighborhoods/towns.
 * * @ai_usage Use for heatmap visualizations and high-level area comparisons.
 */
export const analyticsNeighborhoodScores = sqliteTable('analytics_neighborhood_scores', {
    id: integer('id').primaryKey(),
    town: text('town').notNull(),
    walkabilityScore: real('walkability_score'), // 0-100
    foodAccessibilityScore: real('food_accessibility_score'), // 0-100
    transportScore: real('transport_score'), // 0-100
});

/**
 * **AI Property Listings**
 * * "Realtor-style" narratives and explanations generated by LLMs.
 * * @ai_usage Use this to display the "AI Realtor Pitch" on the frontend.
 */
export const aiPropertyListings = sqliteTable('ai_property_listings', {
    id: integer('id').primaryKey(),
    blockId: integer('block_id').references(() => enrichedHdbBlocks.id).notNull(),

    // Content - AI Generated
    listingNarrative: text('listing_narrative'), // The "Realtor Pitch"
    overallReasoning: text('overall_reasoning'), // High-level summary

    // Analysis Lists (JSON arrays)
    proList: text('pro_list'), // e.g. ["High rental yield", "Near MRT"]
    conList: text('con_list'), // e.g. ["Short remaining lease", "Noisy area"]

    // Metadata
    modelName: text('model_name'),
    promptUsed: text('prompt_used'),
    generatedAt: text('generated_at').notNull(),
});

/**
 * **HDB Valuation Data**
 * * Granular financial breakdown per flat type within a block.
 */
export const hdbValuationData = sqliteTable('hdb_valuation_data', {
    id: integer('id').primaryKey(),
    blockId: integer('block_id').references(() => enrichedHdbBlocks.id).notNull(),
    flatType: text('flat_type').notNull(), // '3-ROOM', '4-ROOM'

    // Buy Valuation
    estMinValBuy: real('est_min_val_buy'),
    estAvgValBuy: real('est_avg_val_buy'),
    estMaxValBuy: real('est_max_val_buy'),

    // Rent Valuation
    estMinValRent: real('est_min_val_rent'),
    estAvgValRent: real('est_avg_val_rent'),
    estMaxValRent: real('est_max_val_rent'),

    // Market Depth
    totalUnits: integer('total_units'),
    latestPurchaseDate: text('latest_purchase_date'),
    avgAnnualPurchases: real('avg_annual_purchases'),
    impliedRentalYield: real('implied_rental_yield'),
    salesVolumeLastYear: integer('sales_volume_last_year'),

    lastEnrichedAt: text('last_enriched_at'),
});

/**
 * **HDB Score-Lah!**
 * * Detailed scoring for lifestyle and investability.
 */
export const hdbScoreLah = sqliteTable('hdb_score_lah', {
    id: integer('id').primaryKey(),
    blockId: integer('block_id').references(() => enrichedHdbBlocks.id).notNull(),

    scoreLah: integer('score_lah'), // Overall Score
    scoreLahRationale: text('score_lah_rationale'),

    // Component Scores (0-100)
    walkability: integer('walkability'),
    walkabilityRationale: text('walkability_rationale'),

    foodAccess: integer('food_access'),
    foodAccessRationale: text('food_access_rationale'),

    hawker: integer('hawker'),
    hawkerRationale: text('hawker_rationale'),

    mrt: integer('mrt'),
    mrtRationale: text('mrt_rationale'),

    bus: integer('bus'),
    busRationale: text('bus_rationale'),

    education: integer('education'),
    educationRationale: text('education_rationale'),

    parks: integer('parks'),
    parksRationale: text('parks_rationale'),

    // Other metrics (Lower is better)
    noiseLevel: integer('noise_level'), // 0-10
    noiseLevelRationale: text('noise_level_rationale'),

    trafficLevel: integer('traffic_level'), // 0-10
    trafficLevelRationale: text('traffic_level_rationale'),
});

/**
 * **User Portfolio**
 * * Tracks properties owned or tracked by users.
 */
export const userPortfolio = sqliteTable('user_portfolio', {
    id: integer('id').primaryKey(),
    userId: text('user_id').notNull(), // UUID from Auth system
    blockId: integer('block_id').references(() => enrichedHdbBlocks.id).notNull(),

    // Specific Unit Details
    flatType: text('flat_type'), // '4-ROOM'
    unitNumber: text('unit_number'), // Optional (Encrypted concept)

    // Status
    ownershipStatus: text('ownership_status').notNull(), // 'OWNED', 'INHERITANCE_FUTURE', 'TRACKING'

    // Financials
    acquisitionDate: text('acquisition_date'),
    acquisitionPrice: real('acquisition_price'),
    currentRent: real('current_rent'), // If rented out

    createdAt: text('created_at').notNull(),
});

/**
 * **Portfolio Analysis**
 * * AI-driven insights for specific portfolio items.
 */
export const portfolioAnalysis = sqliteTable('portfolio_analysis', {
    id: integer('id').primaryKey(),
    portfolioId: integer('portfolio_id').references(() => userPortfolio.id).notNull(),
    generatedAt: text('generated_at').notNull(),

    // Rent Analysis
    rentGap: real('rent_gap'), // (Current Rent - Market Avg)
    rentAdvice: text('rent_advice'), // AI text: "Raise rent by $200"

    // Resale Analysis
    marketValueGap: real('market_value_gap'), // (Est. Value - Acquisition Price)
    resaleOutlook: text('resale_outlook'), // "Bullish", "Bearish", "Stable"
    // Lifestyle/Score Impact
    scoreLahImpact: text('score_lah_impact'), // "High walkability adds ~$20k value"

    // Strategic Advice
    aiActionItems: text('ai_action_items'), // JSON list: ["Renovate kitchen", "Review lease"]
});

/**
 * **HDB Frontend Data**
 * * Pre-generated assets and links for UI display.
 */
export const hdbFrontendData = sqliteTable('hdb_frontend_data', {
    id: integer('id').primaryKey(),
    blockId: integer('block_id').references(() => enrichedHdbBlocks.id).notNull(),
    googleStreetViewUrl: text('google_street_view_url'),
    lastEnrichedAt: text('last_enriched_at'),
});

// Type Exports
export type EnrichedHdbBlock = InferSelectModel<typeof enrichedHdbBlocks>;
export type HdbScoreLah = InferSelectModel<typeof hdbScoreLah>;
export type HdbValuationData = InferSelectModel<typeof hdbValuationData>;
export type HdbFrontendData = InferSelectModel<typeof hdbFrontendData>;
export type UserPortfolio = InferSelectModel<typeof userPortfolio>;
export type PortfolioAnalysis = InferSelectModel<typeof portfolioAnalysis>;

export type NewPortfolioAnalysis = InferInsertModel<typeof portfolioAnalysis>;

